### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [kengkeelim/jamming#4]
Overall, you did a good job on this project.  You had a nice organized file structure and implemented the functionality requested of you.  A few things to improve upon would be avoiding the mutation of state directly in your functions.  Another thing would be to tone down the commenting a bit.  Comments are a great tool to enhance readability of your code, but adding too many comments can make the code look disjointed.  You had many large blocks of comments within each function, causing them to be had to parse and read.  Besides those two things, good job.

**Comment by kengkeelim** [comment]
Thank you for your time and support, Tom.
I have made correction accordingly.
